### Create new
POST {{url}}/articles
x-category-id: 21
Content-Type: application/json

{
  "name": "Merlot",
  "description": "a tasty red wine, try it!",
  "price": 5.20,
  "picture": "abcd"
}

### Modify
PUT {{url}}/articles/1
Content-Type: application/json

{
  "name": "Chardonnay",
  "description": "a tasty white wine, try it!",
  "price": 6.30,
  "picture": "abcd"
}

### Get all
GET {{url}}/articles

### Get single
GET {{url}}/articles/1

### Delete
DELETE {{url}}/articles/1
