### Create new
POST {{url}}/tables
Content-Type: application/json

{
  "name": "Letzte Ecke",
  "seatCount": 5,
  "active": false
}

### Modify
PUT {{url}}/tables/1
Content-Type: application/json

{
  "name": "Tresen"
}

### Get all
GET {{url}}/tables
#Authorization: Basic Ym9iOmZvbw==

### Get single
GET {{url}}/tables/1

### Delete
DELETE {{url}}/tables/1
