### Create new
POST {{url}}/tables
Content-Type: application/json

{
  "name": "Letzte Ecke",
  "active": false
}

### Modify
PUT {{url}}/tables/1
Content-Type: application/json

{
  "name": "Tresen"
}

### Get all
GET {{url}}/tables

### Get single
GET {{url}}/tables/1

### Delete
DELETE {{url}}/tables/1
